### ISSUE TITLE
tmux session

### ISSUE THREAD

**Issue by vbauerster** [vovkasm/input-source-switcher#3] opened 2015-07-27 08:07 UTC
Doesn't switch under tmux session.
Steps to reproduce:

1.>tmux new-session -s test
2.>vim test.txt

After, switch keyboard layout in insert mode, then return back to normal mode. Nothing happens, layout remains in the same state as it was in insert mode.

**Comment by vovkasm** [comment] 2015-07-27 09:10
This can be related to OS X namespaces. Can you try run shell with `reattach-to-user-namespace` (can be installed from Homebrew)?

See this blog post for quick setup guide: [How to Copy and Paste with tmux on Mac OS X](https://robots.thoughtbot.com/how-to-copy-and-paste-with-tmux-on-mac-os-x).
Also long explanation can be found here: https://github.com/ChrisJohnsen/tmux-MacOSX-pasteboard/blob/master/README.md

If this doesn't help, can you please send you versions of the Mac OS X and tmux?

**Comment by vbauerster** [comment] 2015-07-27 13:22
I've tried putting the following line, to my tmux.conf
`set-option -g default-command "reattach-to-user-namespace -l zsh"`
but it didn't help.

tmux: stable 2.0
Mac: 10.10.4

tmux was installed from brew.
PS: Have tried [this lib](https://github.com/myshov/libxkbswitch-macosx) and it is working under tmux without any `reattach-to-user-namespace` option.

**Comment by vovkasm** [comment] 2015-07-27 14:24
Thank you for feedback. I'am glad, that reattach-to-user-namespace no longer needed for modern versions of OS X.

But I can't reproduce the failure. For me it worked properly with you test case, so I will try to test it in a clean environment.

This is my current environment:

```
OS X: 10.10.4
$ tmux -V
tmux 2.0
$ issw -V
Input Source Switcher version 0.3
$ vim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jul 12 2015 09:36:11)
MacOS X (unix) version
Included patches: 1-769
Compiled by Homebrew
Huge version with MacVim GUI.  Features included (+) or not (-):
...
Linking: clang   -L. -L/usr/local/lib -L. -L/usr/local/lib -F/usr/local/Cellar/python/2.7.10_1/Frameworks -L/usr/local/Cellar/python/2.7.10_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/config -lpython2.7 -framework CoreFoundation -L/usr/local/lib -o Vim -framework Cocoa -framework Carbon       -lm  -lncurses -liconv -framework Cocoa   -fstack-protector  -L/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE -lperl -F/usr/local/Cellar/python/2.7.10_1/Frameworks -framework Python  -F/System/Library/Frameworks -framework Tcl -framework CoreFoundation -framework Ruby

vim configs from https://github.com/vovkasm/vimrc.git 
```

**Comment by vbauerster** [comment] 2015-07-29 09:25
By the way I use [Prezto](https://github.com/wbauer/prezto) shell subset of zsh. Not sure but maybe it is affecting in some way.

**Comment by vovkasm** [comment] 2015-12-28 23:06
Unfortunately I still can't reproduce the failure, sorry. So if anyone can, please debug it, or provide additional info. As a suggestion before real debugging, you can try check system errors in Console application.

**Comment by vbauerster** [comment] 2017-01-20 06:15
Sorry for late response, but it seems that it works in latest tmux.
My tmux.conf sets [reattach-to-user-namespace](https://github.com/vbauerster/dotfiles/blob/master/tmux.conf#L31-L32) option.

**Comment by vovkasm** [comment] 2017-01-20 06:17
So can we close this issue?

**Comment by vbauerster** [comment] 2017-01-20 06:17
yes

**Closed as completed** 2017-01-20 06:20 UTC
Labels: help wanted
